export function FinalHospedeForm(){
	return(
		<>
			<div className="flex flex-col items-center justify-center">
						<h1 className="font-bold">Cadastro Realizado com sucesso!</h1>
						<p>Lista com informações fornecidas</p>
						<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores repudiandae commodi sunt labore, eveniet veritatis hic pariatur quas architecto saepe, laborum repellendus quod voluptate ea, quos fuga iure tempore! Incidunt labore, repellendus, quae nulla dicta dolor neque asperiores similique tempore aliquam magni possimus a expedita minima corrupti, maiores facilis quia architecto molestias? Soluta modi magni quos sit, dolores praesentium accusamus aut quibusdam est a accusantium animi cupiditate. Amet commodi quod natus explicabo quis cupiditate iusto quas excepturi aliquam, nostrum vero quo ad dolor laudantium. Quod perspiciatis cum voluptatem assumenda. Omnis, harum molestias laudantium ipsa voluptatibus tenetur, facilis optio deserunt consequatur, officia itaque quasi ad mollitia adipisci tempore. Totam neque quod eveniet maiores vel similique necessitatibus officia ipsum quisquam magnam molestias voluptates, earum laboriosam? Corporis impedit quisquam eligendi, aperiam aspernatur provident nihil ea non deserunt repellendus sapiente amet, perferendis sequi et laboriosam blanditiis quam perspiciatis ratione accusantium illum. Neque cumque dolorem maiores provident animi aliquam debitis deserunt fugiat facilis corporis! Facere dolor laboriosam accusantium laudantium, veniam unde accusamus sint aliquid harum minus modi ad ratione, nam corrupti odit consectetur id ipsa? Cumque, sint aliquid consectetur doloremque, perspiciatis necessitatibus ea possimus ab beatae fuga quod. Odit error esse optio est culpa unde, possimus illum ea blanditiis, exercitationem amet quod libero nobis eaque, quia explicabo inventore? Cupiditate mollitia perspiciatis quaerat esse veritatis officiis, corrupti, dolores eveniet alias, natus ex incidunt! Qui placeat quas suscipit cumque itaque voluptatum quae molestiae labore possimus ab temporibus iusto ratione consequatur, excepturi dolorem, magnam eius eaque voluptate unde dolore necessitatibus. Cum autem perspiciatis sed aliquam qui non. Inventore beatae distinctio veniam harum fugit fugiat dolorum illum odit. Quod deleniti rem amet numquam fugit. Hic recusandae nobis ad omnis pariatur in, eum exercitationem aspernatur cupiditate suscipit nam officia nihil. Mollitia, recusandae assumenda tenetur quis officia dolore necessitatibus ab placeat.</p>
					</div>
		</>
	)
};